name: Run continous integration (CI) on a schedule
on:
  push:
    branches:
      - main
defaults:
  run:
    shell: bash
env:
  ORG: mtrmarko
jobs:
  test-platform:
    name: Checkout, Start and Test Nuclearn Platform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout NPI Test Repo
        uses: actions/checkout@v3
      - name: Github context
        shell: bash
        run: |
          echo "Working directory is $PWD"
          echo "Github workspace directory is ${{ env.GITHUB_WORKSPACE }}"
      - name: checkout gha-api
        uses: actions/checkout@v3
        with:
          repository: ${{ env.ORG }}/gha-api
          path: gha-api
          token: ${{secrets.CI_PAT}}
          ref: main
          clean: false
      - name: Github context2
        shell: bash
        run: echo "Working directory is $PWD"
      - name: Build container
        id: start-platform
        uses: ./.github/actions/build-container
