name: Run continous integration (CI) on a schedule
on:
  push:
    branches:
      - main
defaults:
  run:
    shell: bash
env:
  ORG: mtrmarko
jobs:
  checkout-repos:
    name: Checkout, Start and Test Nuclearn Platform
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: [gha-api, gha-front, gha-integ]
    outputs:
      is_changed: ${{ steps.echo-working-dir.outputs.is_changed }}
    steps:
      - name: Checkout repos
        uses: actions/checkout@v3
        with:
          repository: mtrmarko/${{ matrix.repo }}
          token: ${{secrets.CI_PAT}}
          ref: main
          clean: false
          path: ${{ matrix.repo }}
      - name: Echo working directory
        id: echo-working-dir
        shell: bash
        run: |
          echo "Working directory after ${{matrix.repo}} is $PWD"
          echo "is_changed=true" >> $GITHUB_OUTPUT
  start-platform:
    name: Start platform
    runs-on: ubuntu-latest
    needs: checkout-repos
    steps:
      - name: Echo working directory
        shell: bash
        run: |
          echo "Working directory is $PWD"
          echo "${{ toJson(jobs) }}"
#       - name: Build container
#         id: start-platform
#         uses: ./gha-integ/.github/actions/build-container
