name: Run continous integration (CI) on a schedule
on:
  push:
    branches:
      - main
defaults:
  run:
    shell: bash
env:
  ORG: mtrmarko
jobs:
  checkout-repos:
    name: Checkout, Start and Test Nuclearn Platform
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: [gha-api, gha-front, gha-integ]
    steps:
      - name: Checkout repos
        uses: actions/checkout@v3
        with:
          repository: mtrmarko/${{ matrix.repo }}
          token: ${{secrets.CI_PAT}}
          ref: main
          clean: false
          path: ${{ matrix.repo }}
      - name: Echo working directory
        shell: bash
        run: |
          echo "Working directory after ${{matrix.repo}} is $PWD"
  start-platform:
    name: Start platform
    runs-on: ubuntu-latest
    needs: checkout-repos
    steps:
      - name: Echo working directory
        shell: bash
        run: |
          echo "Working directory after ${{matrix.repo}} is $PWD"
      - name: Build container
        id: start-platform
        uses: ./gha-integ/.github/actions/build-container
