name: Run continous integration (CI) on a schedule
on:
  push:
    branches:
      - main
defaults:
  run:
    shell: bash
env:
  ORG: mtrmarko
jobs:
  checkout-repos:
    name: Checkout, Start and Test Nuclearn Platform
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - repo: gha-api
            branch: main
            is_changed: false
          - repo: gha-front
            branch: main
            is_changed: false
          - repo: gha-integ
            branch: main
            is_changed: false
    outputs:
      # Github Actions do not have the ability to export
      # outputs for each matrix instance into a single list
      # of values. Instead, single output variable is dumped
      # and set to the value of the last instance completion
      # https://github.com/orgs/community/discussions/17245
      # https://github.com/actions/runner/issues/1835
      # https://stackoverflow.com/questions/70287603/github-actions-dynamic-outputs-for-job-with-strategy-matrix
      is_changed_api: ${{ steps.echo-working-dir.outputs.is_changed_gha-api }}
      is_changed_integ: ${{ steps.echo-working-dir.outputs.is_changed_gha-integ }}
      is_changed_front: ${{ steps.echo-working-dir.outputs.is_changed_gha-front }}
    steps:
      - name: Checkout repos
        uses: actions/checkout@v3
        with:
          repository: mtrmarko/${{ matrix.repo }}
          token: ${{secrets.CI_PAT}}
          ref: ${{ matrix.branch }}
          clean: false
          path: ${{ matrix.repo }}
      - name: Echo working directory
        id: echo-working-dir
        shell: bash
        run: |
          echo "Working directory after ${{matrix.repo}} is $PWD"
          echo "is_changed_${{ matrix.repo }}=${{ matrix.is_changed }}"
          echo "is_changed_${{ matrix.repo }}=${{ matrix.is_changed }}" >> $GITHUB_OUTPUT
  start-platform:
    name: Start platform
    runs-on: ubuntu-latest
    needs: checkout-repos
    if: ${{ needs.checkout-repos.outputs.is_changed_api || needs.checkout-repos.outputs.is_changed_api || needs.checkout-repos.outputs.is_changed_api }}
    steps:
      - name: Echo working directory
        shell: bash
        run: |
          echo "Working directory is $PWD"
          echo "${{ toJson(needs) }}"
#       - name: Build container
#         id: start-platform
#         uses: ./gha-integ/.github/actions/build-container
