name: Test2
on:
   push:
     branches:
       - main
defaults:
  run:
    shell: bash
env:
  ORG: $(date)
jobs:
  checkout-repos:
    name: Checkout, Start and Test Nuclearn Platform
    runs-on: ubuntu-latest
    run: |
      echo "${{ env.ORG }}"
