name: Run continous integration (CI) on a schedule
on:
  push:
    branches:
      - main
env:
  BRANCH: NAI-570-fix-and-make-ci-github-action-scheduled
jobs:
  checkout-repos:
    name: Checkout, Start and Test Nuclearn Platform
    runs-on: ubuntu-latest
    strategy:
      matrix:
        org: [nuclearnai]
        branch: [ env.BRANCH ]
        repo: [model-runtime-engine, frontend, np-integration-testing]
        process_devenv: [false]
        include:
          - repo: np-integration-testing
#             org: nuclearnai
#             branch: NAI-570-fix-and-make-ci-github-action-scheduled
            process_devenv: false
            docker_image: np_integration_testing_dev
          - repo: model-runtime-engine
#             org: nuclearnai
#             branch: NAI-570-fix-and-make-ci-github-action-scheduled
            process_devenv: false
            docker-image: np_mreapi_dev
          - repo: model-runtime-engine
#             org: nuclearnai
#             branch: NAI-570-fix-and-make-ci-github-action-scheduled
            process_devenv: true
            docker-image: np_mreapi_devenv
          - repo: frontend
#             org: nuclearnai
#             branch: NAI-570-fix-and-make-ci-github-action-scheduled
            process_devenv: false
            docker-image: np_frontend_dev
          - repo: frontend
#             org: nuclearnai
#             branch: NAI-570-fix-and-make-ci-github-action-scheduled
            process_devenv: true
            docker-image: np_frontend_devenv
    steps:
      - name: test-matrix
        shell: bash
        run: |
          echo "org is ${{ matrix.org }}"
          echo "branch is ${{ matrix.branch }}"
          echo "repo is ${{ matrix.repo }}"
          echo "has dev env is ${{ matrix.process_devenv }}"
