name: Test2
on:
   push:
     branches:
       - main
defaults:
  run:
    shell: bash
env:
  ORG: $(date +%Y%m%d%H%M%S)
jobs:
  checkout-repos:
     runs-on: ubuntu-latest
     steps:
      - name: Checkout, Start and Test Nuclearn Platform
        run: |
            echo "${{ env.ORG }}"
