name: Run continous integration (CI) on a schedule
on:
  push:
    branches:
      - main
jobs:
  checkout-repos:
    name: Checkout, Start and Test Nuclearn Platform
    runs-on: ubuntu-latest
    strategy:
      matrix:
        org: [nuclearnai]
        branch: [NAI-570-fix-and-make-ci-github-action-scheduled]
        include:
          - repo: np_integration_testing
            process_devenv: false
            docker_image: np_integration_testing_dev
          - repo: model-runtime-engine
            process_devenv: false
            docker-image: np_mreapi_dev
          - repo: model-runtime-engine
            process_devenv: true
            docker-image: np_mreapi_devenv
          - repo: frontend
            process_devenv: false
            docker-image: np_frontend_dev
          - repo: frontend
            process_devenv: true
            docker-image: np_frontend_devenv
    steps:
      - name: test-matrix
        shell: bash
        run: |
          echo "org is ${{ matrix.org }}"
          echo "branch is ${{ matrix.branch }}"
          echo "repo is ${{ matrix.repo }}"
          echo "has dev env is ${{ matrix.has_devenv }}"
